### ISSUE TITLE
Crash with enumcreaturetype

### ISSUE THREAD

**Issue by EnderT5** [kegare/Cavern#1] opened 2016-05-11 17:31 UTC
crash is fixed when i remove the cavern mod, it isnt a abyssalcraft bug.

http://pastebin.com/gujLspkw

**Comment by kegare** [comment] 2016-05-11 22:15
Please try to change some config.
cavern-dimension.cfg -> **I:monsterSpawn=0**
caveland-dimension.cfg -> **I:monsterSpawn=0**

**Comment by kegare** [comment] 2016-05-11 22:31
Also, please try to check in minimum environment.
(Install only: Forge, Cavern)

Cavern mod may not be the cause

**Comment by kegare** [comment] 2016-06-05 12:07
Fixed on 1.0.7 build.

**Closed by kegare** 2016-06-05 12:07 UTC
